kind: pipeline
name: build

trigger:
  branch:
  - master
  - test3

steps:
- name: build-webapp
  commands:
   - ls -larth
---
kind: pipeline
name: deploy

trigger:
  branch:
  - master
  - test3

depends_on:
- build

steps:
  commands:
   - cat /etc/passwd